add tests
MalyshM/vkr pull request #43
Opened 2024-04-14 12:46 UTC by snnus

speciality comparison page tests

2024-04-14 15:16 UTC, MalyshM requested changes
доделай остальные роуты, тут в целом все норм
вот пример на роут 
http://moais-dashboard.ru:8082/api/speciality_kr_total_points_attendance_dynamic
На такие роуты дохуя тестов,
Токен админа, True
Токен админа, False
Токен препода, True
Токен препода, False
Токен админа, false, "Павлова Елена Александровна,Плотоненко Юрий Анатольевич"
Потом неправильные тесты
Неправильный токен
Правильный токен, не указан bool
Токен админа, False, "asd,asd" Строка
Токен препода, false, "Павлова Елена Александровна,Плотоненко Юрий Анатольевич"

токен препода это к примеру 
{
  "FIO": "Павлова Елена Александровна",
  "username": "Павлова Елена Александровна",
  "password": "Павлова Елена Александровна",
  "email": "Павлова Елена Александровна"
}
по роуту 
http://moais-dashboard.ru:8082/api/login_standard

2024-04-14 15:16 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            # self.assertIsInstance(item["Stud_speciality"], str)
почему закомменчено?

2024-04-16 09:42 UTC, snnus commented on backend/speciality_comparison_page_tests.py
> +            # self.assertIsInstance(item["Stud_speciality"], str)
потому что выдаёт keyerror, ключ я взял из описания роута, попробовал также просто speciality

2024-04-17 11:20 UTC, MalyshM requested changes
жду новую версия по тому, что писал в тг(написал это только чтобы мне пришел увед)

2024-04-18 07:05 UTC, MalyshM requested changes

2024-04-18 07:05 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            self.assertIsInstance(item["total_points"] * 1.0, float) # чтобы привести к флоуту (нечисловое значение энивей не приведётся)te
self.assertIsInstance(float(item["total_points"]), float)

проверять float(item["total_points"]) на NaN

2024-04-18 07:05 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            self.assertIsInstance(item["studs_in_speciality"], int)
1 поля не хватает

2024-04-18 07:05 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            # self.assertIsInstance(total_points['teacher_name'], str) # keyerror
подобные комменты убрать

2024-04-18 07:05 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            # self.assertIsInstance(total_points['teacher_id'], int) # keyerror
убрать

2024-04-18 07:05 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            # self.assertIsInstance(total_points['teacher_id'], int) # keyerror
убрать

2024-04-18 07:05 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            # self.assertIsInstance(total_points['teacher_id'], int) # keyerror
убрать

2024-04-18 07:05 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            self.assertIsInstance(total_points['teacher_id'], int)
убрать лишние поля

2024-04-18 07:05 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            # self.assertIsInstance(total_points['teacher_id'], int)
убрать

2024-04-18 07:05 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +    def test_speciality_kr_attendance_dynamic4(self):
переназови, не хватает fail

2024-04-18 07:05 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            # self.assertIsInstance(total_points['teacher_id'], int) # keyerror
убрать

2024-04-18 07:05 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            # self.assertIsInstance(total_points['teacher_id'], int) # keyerror
убрать

2024-04-18 07:05 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            # self.assertIsInstance(total_points['teacher_id'], int) # keyerror
убрать

2024-04-18 07:07 UTC, MalyshM commented on backend/speciality_comparison_page_tests.py
> +            # self.assertIsInstance(total_points['teacher_id'], int) # keyerror
еще нужно нажать ctrl alt l после работы

2024-04-21 04:35 UTC, MalyshM approved these changes

2024-04-21 04:35 UTC, merged